name: 'Deploy'
on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: write

jobs:
  Deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    env:
      KAFKA_BOOTSTRAP_SERVER: ${{ secrets:KAFKA_BOOTSTRAP_SERVER }}
      KAFKA_REQUEST_TOPIC: ${{ secrets:KAFKA_REQUEST_TOPIC }}
      KAFKA_REQUEST_CONSUMER_GROUP_ID: ${{ secrets:KAFKA_REQUEST_CONSUMER_GROUP_ID }}
      KAFKA_BROKER_SASL_SCRAM_USERNAME: ${{ secrets:KAFKA_BROKER_SASL_SCRAM_USERNAME }}
      KAFKA_BROKER_SASL_SCRAM_PASSWORD: ${{ secrets:KAFKA_BROKER_SASL_SCRAM_PASSWORD }}
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Setup Go environment
      uses: actions/setup-go@v5
      
    # This step builds the Go application and creates a zip file containing the binary
    # It is important to note that the binary must be named "bootstrap"
    - name: Build Go application
      run: |    
        rm -rf build && make build && make zip
    
    # Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install the latest serverless
      run: npm i serverless -g
    
    - name: Serverless deploy
      uses: serverless/github-action@v3.2
      with:
        args: deploy --verbose